export type MarketInstrument = {
  symbol: string;
  name: string;
  exchange: "NASDAQ" | "NYSE" | "ARCA";
  assetType: "stock" | "etf";
  sector: string;
  description: string;
  basePrice: number;
  volatility: number;
  logoColor: string;
  whyItMoves: string[];
};

export const MARKET_CATALOG: MarketInstrument[] = [
  {
    symbol: "AAPL",
    name: "Apple",
    exchange: "NASDAQ",
    assetType: "stock",
    sector: "Technology",
    description: "Designs phones, computers, wearables, and digital services used around the world.",
    basePrice: 218.42,
    volatility: 0.018,
    logoColor: "#2b3431",
    whyItMoves: ["iPhone and services sales", "new product demand", "global supply costs"],
  },
  {
    symbol: "MSFT",
    name: "Microsoft",
    exchange: "NASDAQ",
    assetType: "stock",
    sector: "Technology",
    description: "Builds software, cloud computing, gaming, and artificial-intelligence tools.",
    basePrice: 449.18,
    volatility: 0.016,
    logoColor: "#246b5b",
    whyItMoves: ["cloud growth", "business software demand", "AI investment"],
  },
  {
    symbol: "NVDA",
    name: "NVIDIA",
    exchange: "NASDAQ",
    assetType: "stock",
    sector: "Technology",
    description: "Creates computing chips and software used for graphics and artificial intelligence.",
    basePrice: 142.62,
    volatility: 0.032,
    logoColor: "#4b7b35",
    whyItMoves: ["AI chip demand", "data-center spending", "chip supply"],
  },
  {
    symbol: "AMZN",
    name: "Amazon",
    exchange: "NASDAQ",
    assetType: "stock",
    sector: "Consumer",
    description: "Operates online stores, cloud computing, entertainment, and delivery networks.",
    basePrice: 201.36,
    volatility: 0.021,
    logoColor: "#7b5628",
    whyItMoves: ["online shopping", "cloud revenue", "delivery costs"],
  },
  {
    symbol: "GOOGL",
    name: "Alphabet",
    exchange: "NASDAQ",
    assetType: "stock",
    sector: "Communication",
    description: "Runs Google Search, YouTube, Android, cloud services, and other technology products.",
    basePrice: 176.71,
    volatility: 0.019,
    logoColor: "#365f9d",
    whyItMoves: ["advertising demand", "cloud growth", "technology regulation"],
  },
  {
    symbol: "DIS",
    name: "Walt Disney",
    exchange: "NYSE",
    assetType: "stock",
    sector: "Communication",
    description: "Creates entertainment and operates streaming services, studios, parks, and resorts.",
    basePrice: 112.04,
    volatility: 0.021,
    logoColor: "#37526f",
    whyItMoves: ["park attendance", "streaming subscribers", "movie performance"],
  },
  {
    symbol: "KO",
    name: "Coca-Cola",
    exchange: "NYSE",
    assetType: "stock",
    sector: "Consumer Staples",
    description: "Makes and sells beverages through a global network of brands and bottlers.",
    basePrice: 70.33,
    volatility: 0.009,
    logoColor: "#a33d35",
    whyItMoves: ["drink sales", "ingredient costs", "currency changes"],
  },
  {
    symbol: "NKE",
    name: "Nike",
    exchange: "NYSE",
    assetType: "stock",
    sector: "Consumer",
    description: "Designs and sells athletic shoes, clothing, equipment, and digital experiences.",
    basePrice: 78.55,
    volatility: 0.022,
    logoColor: "#443c34",
    whyItMoves: ["consumer demand", "inventory levels", "sportswear competition"],
  },
  {
    symbol: "SPY",
    name: "SPDR S&P 500 ETF",
    exchange: "ARCA",
    assetType: "etf",
    sector: "Broad Market",
    description: "A fund that holds shares in many large U.S. companies and tracks the S&P 500 index.",
    basePrice: 592.16,
    volatility: 0.01,
    logoColor: "#465f7a",
    whyItMoves: ["the broad economy", "interest rates", "large-company earnings"],
  },
  {
    symbol: "QQQ",
    name: "Invesco QQQ ETF",
    exchange: "NASDAQ",
    assetType: "etf",
    sector: "Growth Index",
    description: "A fund that tracks 100 large non-financial companies listed on Nasdaq.",
    basePrice: 517.29,
    volatility: 0.014,
    logoColor: "#5b477d",
    whyItMoves: ["technology earnings", "interest rates", "growth expectations"],
  },
  {
    symbol: "VTI",
    name: "Vanguard Total Stock Market ETF",
    exchange: "ARCA",
    assetType: "etf",
    sector: "Broad Market",
    description: "A fund holding thousands of U.S. companies across large, medium, and small sizes.",
    basePrice: 291.87,
    volatility: 0.01,
    logoColor: "#6f443c",
    whyItMoves: ["the U.S. economy", "company profits", "investor confidence"],
  },
  {
    symbol: "COST",
    name: "Costco",
    exchange: "NASDAQ",
    assetType: "stock",
    sector: "Consumer Staples",
    description: "Operates membership warehouses selling food, household goods, fuel, and services.",
    basePrice: 914.22,
    volatility: 0.015,
    logoColor: "#315b75",
    whyItMoves: ["membership growth", "store sales", "product costs"],
  },
];

export const MARKET_CATALOG_BY_SYMBOL = new Map(
  MARKET_CATALOG.map((instrument) => [instrument.symbol, instrument]),
);
