import Link from "next/link";
import { AlertTriangle, ArrowRight, BookOpenCheck, ClipboardCheck, Pause, UsersRound } from "lucide-react";

import { getTeacherGameDTO } from "@/lib/data/teacher";
import { formatMoney, formatPercent } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function TeacherDemoPage() {
  const data = await getTeacherGameDTO();
  if (!data) return <p>Demo game not found. Run the database seed.</p>;
  return <>
    <div className="page-title"><div><span className="eyebrow">Teacher command center</span><h1>Good afternoon, Ms. Rivera.</h1><p className="muted" style={{ margin: ".6rem 0 0" }}>{data.classroom?.name} · {data.game.startsAt.toLocaleDateString("en-US", { month: "short", day: "numeric" })}–{data.game.endsAt.toLocaleDateString("en-US", { month: "short", day: "numeric" })}</p></div><button className="button-secondary" type="button" title="Disabled in public demo"><Pause size={17} /> Pause trading</button></div>
    <section className="stat-grid" style={{ gridTemplateColumns: "repeat(4,1fr)" }}><TeacherStat label="Students" value={`${data.stats.students}`} note={`${data.stats.activeToday} active today`} /><TeacherStat label="Class equity" value={formatMoney(data.stats.classEquity, { compact: true })} note="Across all portfolios" /><TeacherStat label="Orders observed" value={`${data.stats.orders}`} note="Recent replay activity" /><TeacherStat label="Labs completed" value={`${data.stats.lessonsComplete}`} note="Separate from ranking" /></section>
    <div className="portfolio-layout">
      <section className="card table-card"><div className="table-header"><div><span className="eyebrow">Class pulse</span><h2 style={{ margin: ".35rem 0 0" }}>Student overview</h2></div><Link className="button-quiet" href="/teacher/demo/roster">Full roster →</Link></div><table className="data-table"><thead><tr><th>Student</th><th>Rank</th><th>Portfolio</th><th>Return</th><th>Learning</th><th>Journal</th></tr></thead><tbody>{data.roster.slice().sort((a,b) => (a.rank ?? 99) - (b.rank ?? 99)).slice(0, 7).map((student) => <tr key={student.id}><td><strong>{student.displayName}</strong><span className="muted" style={{ display: "block", fontSize: ".7rem" }}>{student.username}</span></td><td>#{student.rank}</td><td><strong>{formatMoney(student.equity)}</strong></td><td className={student.returnPercent >= 0 ? "positive" : "negative"}>{formatPercent(student.returnPercent)}</td><td>{student.lessonsCompleted}/{data.lessons.length}</td><td>{student.journalCount}</td></tr>)}</tbody></table></section>
      <aside className="side-stack"><section className="card" style={{ padding: "1.2rem" }}><span className="eyebrow">Needs attention</span><div className="compact-list" style={{ marginTop: ".7rem" }}><Alert icon={<AlertTriangle />} title="4 concentrated portfolios" copy="One holding is near the 30% class limit." /><Alert icon={<BookOpenCheck />} title="7 students have a lab due" copy="Risk and diversification closes Friday." /><Alert icon={<ClipboardCheck />} title="3 thin rationales" copy="Consider a small-group evidence check." /></div></section><section className="card" style={{ padding: "1.2rem", background: "#e4f5f7" }}><UsersRound size={21} /><h3 style={{ margin: ".7rem 0 .4rem" }}>Discussion starter</h3><p className="muted" style={{ fontSize: ".8rem", lineHeight: 1.6 }}>The class holds a lot of technology. Ask: when does shared exposure become a shared risk?</p></section></aside>
    </div>
    <section className="card" style={{ padding: "1.3rem", marginTop: "1rem", display: "flex", alignItems: "center", justifyContent: "space-between", gap: "1rem", flexWrap: "wrap" }}><div><span className="eyebrow">Coming up</span><strong style={{ display: "block", marginTop: ".4rem" }}>Explain one portfolio decision · Due Aug 14</strong></div><Link className="button-primary" href="/teacher/demo/assignments">Review assignment <ArrowRight size={17} /></Link></section>
  </>;
}
function TeacherStat({ label, value, note }: { label: string; value: string; note: string }) { return <div className="card stat-card"><span className="eyebrow">{label}</span><strong>{value}</strong><span className="muted" style={{ fontSize: ".72rem" }}>{note}</span></div>; }
function Alert({ icon, title, copy }: { icon: React.ReactNode; title: string; copy: string }) { return <div className="compact-row" style={{ alignItems: "start" }}><span style={{ color: "#9a5b2b" }}>{icon}</span><div style={{ flex: 1 }}><strong style={{ display: "block", fontSize: ".8rem" }}>{title}</strong><span className="muted" style={{ fontSize: ".7rem", lineHeight: 1.45 }}>{copy}</span></div></div>; }
