import Link from "next/link";
import type { Metadata } from "next";
import { InfoSections, PublicInfoPage } from "@/components/public-info-page";
export const metadata: Metadata = { title: "Fire tablet classroom setup" };
export default function ClassroomGuide() {
  return <PublicInfoPage eyebrow="Teacher guide · 12 Fire tablets" title="Ready before class. Synced after." intro="Students can buy and sell instantly at their latest saved price, with or without internet. Use the Classroom workspace on each assigned tablet."><InfoSections sections={[
    { title: "1. Set up your class", body: <p>Sign in to the <Link href="/teacher/games">teacher workspace</Link>, create an active season with the right dates, and add 12 students in Roster. Use aliases and individual PINs. Keep a list matching each student to Fire 01 through Fire 12.</p> },
    { title: "2. Prepare each Fire once, on good Wi-Fi", body: <ol><li>Update Fire OS and Silk. Use the regular Silk browser in the same device profile each time.</li><li><a href="/join">Sign in</a> with the assigned student’s class code, username, and PIN.</li><li>Open <a href="/classroom">stocks.mikesego.com/classroom</a>. Enter the tablet label and choose Prepare this device.</li><li>Wait for “Ready for offline use” and “All trades backed up.” The default investments and lessons download automatically.</li><li>Bookmark this page in Silk. If your version offers Add to Home Screen or Install, you may use it; installation is optional.</li><li>Turn Wi-Fi off, reload, and confirm the student’s portfolio and saved investments still open. Try a small practice buy and sell, then reconnect and verify backup.</li></ol> },
    { title: "3. Run class with or without internet", body: <p>Keep each student on the same tablet. Use Portfolio, Discover &amp; trade, History, and downloaded learning labs in Classroom. Both buys and sells complete at the saved price shown on the ticket, even when the market is closed. Cash and shares update immediately. Download extra investment symbols before going offline. Trade reflections sync to the journal; assignments, lesson-completion recording, and the class leaderboard use the online workspace.</p> },
    { title: "4. Bring all 12 back to Wi-Fi", body: <p>Put the tablets on good Wi-Fi while charging, with Market Lab open. Uploads retry automatically, and prices refresh about every minute while visible. In Device &amp; help, enable “Keep screen awake” if Silk supports it; otherwise increase the tablet’s Display Sleep timeout. In your teacher season, open Classroom devices and check that every tablet has checked in after class. “Request refresh on all devices” is delivered on their next check-in.</p> },
    { title: "5. Understand the device limits", body: <p>A website cannot reliably wake a sleeping Fire tablet or closed Silk browser. Background sync is attempted where supported, but the dependable routine is to leave Classroom visible while reconnecting. For guaranteed unattended wake/start after closure or reboot, managed kiosk software or a native Fire/Android app would be needed. Actual Silk support varies by device: the built-in offline readiness check and Wi-Fi-off reload on every tablet are the acceptance test.</p> },
    { title: "6. Keep work safe", body: <p>Do not clear Silk website data, use private browsing, reset devices, or switch profiles while work is waiting for backup. Download a private backup from Device &amp; help if a tablet has a persistent sync problem. Before switching students or tablets, sync all trades and choose Release this device. Teacher rule changes and pauses reach offline devices on their next successful download. Sync every device before finalizing standings.</p> },
  ]} /></PublicInfoPage>;
}
