import Link from "next/link";
import { ArrowLeft, ArrowRight } from "lucide-react";

import { createSeason } from "@/app/actions/teacher";
import { Brand } from "@/components/brand";
import { requireTeacher } from "@/lib/auth/teacher";

export const dynamic = "force-dynamic";

export default async function NewSeasonPage() {
  await requireTeacher();
  const now = new Date();
  const end = new Date(now); end.setMonth(end.getMonth() + 2);
  return <><header className="site-header"><div className="container-shell site-header-inner"><Brand /><Link className="button-quiet" href="/teacher/games"><ArrowLeft size={16} /> Your seasons</Link></div></header><main id="main-content" className="container-shell" style={{ padding: "4rem 0 7rem" }}><div style={{ maxWidth: 780, margin: "0 auto" }}><span className="eyebrow">New simulation</span><h1 className="display" style={{ fontSize: "clamp(3.5rem,7vw,6rem)", lineHeight: .9, margin: ".7rem 0 1rem" }}>Create a season.</h1><p className="muted" style={{ lineHeight: 1.7 }}>Start with the classroom and core guardrails. You can add students and refine the allowed universe next.</p><form action={createSeason} className="card-strong" style={{ marginTop: "2rem", padding: "clamp(1.3rem,5vw,2.5rem)", display: "grid", gap: "1.1rem" }}><div className="field"><label htmlFor="schoolName">School or organization</label><input className="input" id="schoolName" name="schoolName" defaultValue="My School" required /></div><div className="lesson-grid"><div className="field"><label htmlFor="classroomName">Class name</label><input className="input" id="classroomName" name="classroomName" defaultValue="Period 1" required /></div><div className="field"><label htmlFor="gradeBand">Grade band</label><select className="select" id="gradeBand" name="gradeBand" defaultValue="6-8"><option value="3-5">Grades 3–5</option><option value="6-8">Grades 6–8</option><option value="mixed">Mixed</option></select></div></div><div className="field"><label htmlFor="seasonName">Season name</label><input className="input" id="seasonName" name="seasonName" defaultValue="Fall Market Lab" required /></div><div className="lesson-grid"><div className="field"><label htmlFor="startsAt">Start date</label><input className="input" type="date" id="startsAt" name="startsAt" defaultValue={now.toISOString().slice(0,10)} required /></div><div className="field"><label htmlFor="endsAt">End date</label><input className="input" type="date" id="endsAt" name="endsAt" defaultValue={end.toISOString().slice(0,10)} required /></div></div><div className="field"><label htmlFor="maxPositionPercent">Maximum one-investment weight</label><select className="select" id="maxPositionPercent" name="maxPositionPercent" defaultValue="30"><option value="20">20%</option><option value="30">30% (recommended)</option><option value="40">40%</option><option value="100">No concentration cap</option></select></div><div className="info-box">This development season will use the deterministic replay feed. It must not be used with real students until a licensed feed and privacy review are complete.</div><button className="button-primary" type="submit">Create season <ArrowRight size={17} /></button></form></div></main></>;
}
