import { AlertTriangle, Database, Pause, Play, Save, ShieldCheck } from "lucide-react";
import { notFound } from "next/navigation";

import { setSeasonStatus, updateSeasonSettings } from "@/app/actions/teacher";
import { getTeacherWorkspace } from "@/lib/data/teacher-workspace";
import { formatMoney } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function TeacherSettingsPage({ params }: PageProps<"/teacher/games/[gameId]/settings">) {
  const { gameId } = await params;
  const workspace = await getTeacherWorkspace(gameId);
  if (!workspace) notFound();
  const { game, data } = workspace;
  const leaderboardVisibility = typeof game.config.leaderboardVisibility === "string" ? game.config.leaderboardVisibility : "class_aliases";
  return <>
    <div className="page-title"><div><span className="eyebrow">Season controls</span><h1>Rules & settings</h1><p className="muted" style={{ margin: ".6rem 0 0" }}>Students see these boundaries before they submit an order.</p></div></div>
    <div className="portfolio-layout"><form action={updateSeasonSettings} className="card teacher-settings-form"><input type="hidden" name="gameId" value={game.id} /><div className="field"><label htmlFor="name">Season name</label><input className="input" id="name" name="name" defaultValue={game.name} required minLength={2} maxLength={100} /></div><div className="teacher-form-grid"><div className="field"><label htmlFor="startsAt">Start date</label><input className="input" id="startsAt" name="startsAt" type="date" defaultValue={toDateInput(game.startsAt)} required /></div><div className="field"><label htmlFor="endsAt">End date</label><input className="input" id="endsAt" name="endsAt" type="date" defaultValue={toDateInput(game.endsAt)} required /></div></div><div className="teacher-form-grid"><div className="field"><label htmlFor="startingCash">Starting cash</label><input className="input" id="startingCash" defaultValue={formatMoney(Number(game.startingCash))} readOnly /><span className="field-hint">Locked after season creation so all students remain comparable.</span></div><div className="field"><label htmlFor="maxPositionPercent">Maximum single position</label><div className="input-suffix"><input className="input" id="maxPositionPercent" name="maxPositionPercent" type="number" min={10} max={100} step={1} defaultValue={Number(game.maxPositionPercent)} required /><span>%</span></div></div></div><fieldset className="teacher-settings-fieldset"><legend className="field-label">Trading and learning rules</legend><Setting name="allowFractional" checked={game.allowFractional} label="Allow fractional shares" /><Setting checked={false} label="Allow short selling" disabled /><Setting checked={false} label="Allow margin borrowing" disabled /><Setting name="rationaleRequired" checked={game.config.rationaleRequired !== false} label="Require a rationale before each order" /></fieldset><div className="field"><label htmlFor="leaderboardVisibility">Leaderboard visibility</label><select className="select" id="leaderboardVisibility" name="leaderboardVisibility" defaultValue={leaderboardVisibility}><option value="class_aliases">Class aliases and portfolio values</option><option value="teacher_only">Teacher only</option><option value="hidden">Hidden during the season</option></select></div><button className="button-primary" type="submit"><Save size={16} /> Save settings</button></form>
      <aside className="side-stack"><div className="card teacher-side-card teacher-data-card"><Database size={21} /><strong>Data mode: live IEX</strong><p className="muted">Alpaca Basic provides real-time IEX prices for this personal demo. All portfolio balances and trades are simulated.</p></div><div className="card teacher-side-card"><ShieldCheck size={21} /><strong>Student privacy</strong><p className="muted">Aliases and PINs are enabled. No student email is required, and stored PINs are one-way hashes.</p></div><div className="card teacher-side-card"><span className="eyebrow">Season access</span><p className="muted">Current status: <strong>{game.status}</strong>. Pausing prevents new simulated trades while preserving all data.</p><form action={setSeasonStatus}><input type="hidden" name="gameId" value={game.id} /><input type="hidden" name="status" value={game.status === "active" ? "paused" : "active"} /><button className="button-secondary full-width" type="submit">{game.status === "active" ? <><Pause size={16} /> Pause all trading</> : <><Play size={16} /> Open trading</>}</button></form></div><details className="card teacher-danger-zone"><summary><AlertTriangle size={16} /> Archive season</summary><p className="muted">Archiving closes the season to students but keeps its records and reports.</p><form action={setSeasonStatus}><input type="hidden" name="gameId" value={game.id} /><input type="hidden" name="status" value="archived" /><button className="button-quiet negative" type="submit">Confirm archive</button></form></details><div className="info-box">{data.roster.length} students · class code <strong>{game.joinCode}</strong></div></aside>
    </div>
  </>;
}

function Setting({ name, checked, label, disabled = false }: { name?: string; checked: boolean; label: string; disabled?: boolean }) { return <label className="teacher-checkbox"><input type="checkbox" name={name} defaultChecked={checked} disabled={disabled} />{label}{disabled ? <span className="muted">Not supported</span> : null}</label>; }
function toDateInput(value: Date) { return value.toISOString().slice(0, 10); }
