import Link from "next/link";
import { AlertTriangle, ArrowRight, BookOpenCheck, ClipboardCheck, Pause, Play, UsersRound } from "lucide-react";
import { notFound } from "next/navigation";

import { setSeasonStatus } from "@/app/actions/teacher";
import { getTeacherWorkspace } from "@/lib/data/teacher-workspace";
import { formatMoney, formatPercent } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function TeacherOverviewPage({ params }: PageProps<"/teacher/games/[gameId]">) {
  const { gameId } = await params;
  const workspace = await getTeacherWorkspace(gameId);
  if (!workspace) notFound();
  const { data } = workspace;
  const firstName = workspace.clerkUser?.firstName ?? workspace.adult.displayName?.split(" ")[0] ?? "Teacher";
  const nextAssignment = data.assignments.find((assignment) => !assignment.dueAt || assignment.dueAt >= new Date()) ?? data.assignments[0];
  const sortedRoster = data.roster.slice().sort((a, b) => (a.rank ?? 999) - (b.rank ?? 999));
  return <>
    <div className="page-title"><div><span className="eyebrow">Teacher command center</span><h1>Good {daypart()}, {firstName}.</h1><p className="muted" style={{ margin: ".6rem 0 0" }}>{data.classroom?.name} · {data.game.startsAt.toLocaleDateString("en-US", { month: "short", day: "numeric" })}–{data.game.endsAt.toLocaleDateString("en-US", { month: "short", day: "numeric" })} · Code <strong>{data.game.joinCode}</strong></p></div><form action={setSeasonStatus}><input type="hidden" name="gameId" value={data.game.id} /><input type="hidden" name="status" value={data.game.status === "active" ? "paused" : "active"} /><button className={data.game.status === "active" ? "button-secondary" : "button-primary"} type="submit">{data.game.status === "active" ? <><Pause size={17} /> Pause trading</> : <><Play size={17} /> Open trading</>}</button></form></div>
    <section className="teacher-stat-grid"><TeacherStat label="Students" value={`${data.stats.students}`} note={`${data.stats.activeToday} active today`} /><TeacherStat label="Class equity" value={formatMoney(data.stats.classEquity, { compact: true })} note="Across all portfolios" /><TeacherStat label="Orders observed" value={`${data.stats.orders}`} note="All simulated activity" /><TeacherStat label="Labs completed" value={`${data.stats.lessonsComplete}`} note={`Across ${data.activeLessons.length} available labs`} /></section>
    {data.roster.length ? <div className="portfolio-layout">
      <section className="card table-card"><div className="table-header"><div><span className="eyebrow">Class pulse</span><h2 style={{ margin: ".35rem 0 0" }}>Student overview</h2></div><Link className="button-quiet" href={`/teacher/games/${gameId}/roster`}>Full roster →</Link></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Student</th><th>Rank</th><th>Portfolio</th><th>Return</th><th>Learning</th><th>Journal</th></tr></thead><tbody>{sortedRoster.slice(0, 7).map((student) => <tr key={student.id}><td><strong>{student.displayName}</strong><span className="muted table-subtext">{student.username}</span></td><td>{student.rank ? `#${student.rank}` : "—"}</td><td><strong>{formatMoney(student.equity)}</strong></td><td className={student.returnPercent >= 0 ? "positive" : "negative"}>{formatPercent(student.returnPercent)}</td><td>{student.lessonsCompleted}/{data.activeLessons.length}</td><td>{student.journalCount}</td></tr>)}</tbody></table></div></section>
      <aside className="side-stack"><section className="card teacher-side-card"><span className="eyebrow">Needs attention</span><div className="compact-list" style={{ marginTop: ".7rem" }}><Alert icon={<AlertTriangle />} title={`${data.attention.inactiveStudentCount} students not active this week`} copy="Check whether they need a login reset or a quick start prompt." /><Alert icon={<BookOpenCheck />} title={`${data.attention.missingAssignmentCount} assignment responses open`} copy={data.assignments.length ? "Open items across current class assignments." : "Create an assignment when you want written evidence."} /><Alert icon={<ClipboardCheck />} title={`${data.attention.thinJournalCount} short reflections`} copy="Entries under 80 characters may benefit from an evidence follow-up." /></div></section><section className="card teacher-discussion-card"><UsersRound size={21} /><h3>Discussion starter</h3><p className="muted">{data.stats.orders ? `Your class has placed ${data.stats.orders} simulated order${data.stats.orders === 1 ? "" : "s"}. Ask one student to separate the quality of the reasoning from what the price did afterward.` : "No trades yet. Ask students what evidence they would want before choosing a company, and what could still make them wrong."}</p></section></aside>
    </div> : <section className="card empty-state"><UsersRound size={32} /><h2>Your class workspace is ready</h2><p className="muted">Add student login cards, choose the learning labs, and create the first assignment. Activity and reporting will fill in automatically as students use the simulation.</p><div className="empty-state-actions"><Link className="button-primary" href={`/teacher/games/${gameId}/roster`}>Add students</Link><Link className="button-secondary" href={`/teacher/games/${gameId}/assignments`}>Plan learning work</Link></div></section>}
    <section className="card coming-up-card"><div><span className="eyebrow">{nextAssignment ? "Coming up" : "Learning work"}</span><strong>{nextAssignment ? `${nextAssignment.title}${nextAssignment.dueAt ? ` · Due ${nextAssignment.dueAt.toLocaleDateString("en-US", { month: "short", day: "numeric" })}` : ""}` : "Create a reflection, research, or comparison assignment"}</strong></div><Link className="button-primary" href={nextAssignment ? `/teacher/games/${gameId}/assignments/${nextAssignment.id}` : `/teacher/games/${gameId}/assignments`}>{nextAssignment ? "Review assignment" : "Create assignment"} <ArrowRight size={17} /></Link></section>
    <section className="card table-card" style={{ marginTop: "1rem" }}><div className="table-header"><div><span className="eyebrow">Recent activity</span><h2 style={{ margin: ".35rem 0 0" }}>What has happened</h2></div><Link className="button-quiet" href={`/teacher/games/${gameId}/activity`}>View all →</Link></div>{data.activity.length ? <div className="compact-list activity-preview">{data.activity.slice(0, 5).map((item) => <div className="compact-row" key={item.id}><div><strong>{item.studentName} · {item.title}</strong><span className="muted table-subtext">{item.detail}</span></div><time className="muted">{formatTime(item.occurredAt)}</time></div>)}</div> : <p className="empty-table-copy">Student sign-ins, orders, lessons, journals, and assignment submissions will appear here.</p>}</section>
  </>;
}

function TeacherStat({ label, value, note }: { label: string; value: string; note: string }) { return <div className="card stat-card"><span className="eyebrow">{label}</span><strong>{value}</strong><span className="muted" style={{ fontSize: ".72rem" }}>{note}</span></div>; }
function Alert({ icon, title, copy }: { icon: React.ReactNode; title: string; copy: string }) { return <div className="compact-row" style={{ alignItems: "start" }}><span className="teacher-alert-icon">{icon}</span><div style={{ flex: 1 }}><strong style={{ display: "block", fontSize: ".8rem" }}>{title}</strong><span className="muted" style={{ fontSize: ".7rem", lineHeight: 1.45 }}>{copy}</span></div></div>; }
function daypart() { const hour = new Date().getHours(); return hour < 12 ? "morning" : hour < 18 ? "afternoon" : "evening"; }
function formatTime(value: Date) { return value.toLocaleString("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }); }
