import { SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";
import Link from "next/link";
import { ArrowRight, FlaskConical, GraduationCap, ShieldCheck } from "lucide-react";

import { Brand } from "@/components/brand";
import { getTeacherIfAuthenticated } from "@/lib/auth/teacher";

export default async function TeacherEntryPage() {
  const teacher = await getTeacherIfAuthenticated();
  return <main id="main-content" className="join-page"><section className="join-story dot-grid"><Brand inverse /><div><span className="eyebrow" style={{ color: "var(--lime)" }}>Educator workspace</span><h1 className="display">Guide the thinking behind the trades.</h1><p style={{ maxWidth: 620, color: "#cad7d3", lineHeight: 1.7 }}>Create seasons, manage classroom-safe accounts, inspect activity, assign learning, and keep financial standings separate from learning evidence.</p></div><span style={{ color: "#cad7d3", fontSize: ".8rem" }}><ShieldCheck size={16} style={{ display: "inline", marginRight: 6 }} />Adult authentication is managed by Clerk.</span></section><section className="join-panel"><div className="join-card"><GraduationCap size={34} /><span className="eyebrow" style={{ display: "block", marginTop: "1rem" }}>Teacher access</span><h2 className="display" style={{ fontSize: "3rem", margin: ".5rem 0 .7rem" }}>{teacher ? `Welcome${teacher.clerkUser?.firstName ? `, ${teacher.clerkUser.firstName}` : ""}.` : "Open your classroom."}</h2><p className="muted" style={{ lineHeight: 1.65, marginBottom: "1.4rem" }}>{teacher ? "Continue to your seasons or explore the seeded classroom demo." : "Sign in with an adult account, create one, or explore the read-only demo first."}</p><div style={{ display: "grid", gap: ".8rem" }}>{teacher ? <><div style={{ display: "flex", gap: ".7rem", alignItems: "center", padding: ".8rem", border: "1px solid var(--line)", borderRadius: ".7rem" }}><UserButton /><span style={{ fontWeight: 800, fontSize: ".82rem" }}>{teacher.adult.email}</span></div><Link className="button-primary" href="/teacher/games">Your seasons <ArrowRight size={17} /></Link></> : <><SignInButton mode="modal" forceRedirectUrl="/teacher/games"><button className="button-primary" type="button">Sign in as a teacher <ArrowRight size={17} /></button></SignInButton><SignUpButton mode="modal" forceRedirectUrl="/teacher/games"><button className="button-secondary" type="button">Create a teacher account</button></SignUpButton></>}<Link className="button-secondary" href="/teacher/demo"><FlaskConical size={17} /> Explore the read-only demo</Link><Link className="button-quiet" href="/educators">Learn about teacher tools →</Link></div></div></section></main>;
}
