import { and, eq } from "drizzle-orm";
import { notFound } from "next/navigation";
import { db } from "@/db";
import { classroomDevices, portfolios, students } from "@/db/schema";
import { getTeacherWorkspace } from "@/lib/data/teacher-workspace";
import { requestClassroomRefresh } from "@/app/actions/classroom-teacher";
import { ClassroomDevicesRefresh } from "@/components/classroom-devices-refresh";
export const dynamic = "force-dynamic";
export default async function DevicesPage({ params }: PageProps<"/teacher/games/[gameId]/devices">) {
  const { gameId } = await params;
  const workspace = await getTeacherWorkspace(gameId);
  if (!workspace) notFound();
  const devices = await db.select({ device: classroomDevices, student: students.displayName }).from(classroomDevices).innerJoin(portfolios, eq(portfolios.id, classroomDevices.portfolioId)).innerJoin(students, eq(students.id, portfolios.studentId)).where(and(eq(portfolios.gameId, gameId), eq(classroomDevices.active, true))).orderBy(classroomDevices.label);
  const now = new Date().getTime();
  return <><ClassroomDevicesRefresh /><div className="page-title"><div><span className="eyebrow">Online and offline classroom</span><h1>Classroom devices</h1><p className="muted">{devices.length} assigned tablets · This page updates every 20 seconds.</p></div><form action={requestClassroomRefresh}><input type="hidden" name="gameId" value={gameId} /><button className="button-primary">Request refresh on all devices</button></form></div><div className="info-box" style={{ marginBottom: "1rem" }}>Put the tablets on good Wi-Fi with Market Lab open. Each uploads its completed trades automatically, then downloads prices. A refresh request reaches connected tablets on their next check-in; it cannot wake a sleeping tablet or closed browser. <a href="/classroom-guide">Read the setup guide.</a></div><section className="card table-card"><div className="table-scroll"><table className="data-table"><thead><tr><th>Tablet</th><th>Student</th><th>Last check-in</th><th>Trades backed up</th><th>Price download</th><th>Refresh request</th></tr></thead><tbody>{devices.map(({ device, student }) => <tr key={device.id}><td><strong>{device.label}</strong></td><td>{student}</td><td>{device.lastSyncAt ? device.lastSyncAt.toLocaleString("en-US", { timeZone: "America/Los_Angeles" }) : "Not yet"}<span className="table-subtext muted">Pacific time{device.lastSyncAt && now - device.lastSyncAt.getTime() < 90_000 ? " · Checked in recently" : " · Awaiting check-in"}</span></td><td>{device.lastSequence}</td><td>{device.pricesRefreshedAt ? device.pricesRefreshedAt.toLocaleString("en-US", { timeZone: "America/Los_Angeles" }) : "Not yet"}</td><td>{!device.refreshRequestedAt ? "Automatic" : device.pricesRefreshedAt && device.pricesRefreshedAt >= device.refreshRequestedAt ? "Delivered" : "Waiting for device"}</td></tr>)}</tbody></table></div>{!devices.length && <p style={{ padding: "1rem" }}>On each tablet, sign in with its student login card, open <a href="/classroom">Classroom</a>, and choose Prepare this device.</p>}</section><p className="muted" style={{ marginTop: "1rem" }}>This is the server’s last confirmed record. A disconnected tablet may contain additional completed trades that have not arrived yet. Check every tablet in after class before comparing final standings. Device assignment is released from the tablet after its trades are backed up.</p></>;
}
