import { KeyRound, LogOut, ShieldCheck, UserRound } from "lucide-react";

import { signOutStudent } from "@/app/actions/student-auth";
import { getStudentSession } from "@/lib/auth/student-session";

export default async function AccountPage() {
  const session = await getStudentSession();
  if (!session) return null;
  return <><div className="page-title"><div><span className="eyebrow">Student account</span><h1>Your classroom identity</h1><p className="muted" style={{ margin: ".6rem 0 0" }}>Market Lab uses only the details your teacher created for this season.</p></div></div><div style={{ maxWidth: 760, display: "grid", gap: "1rem" }}><section className="card" style={{ padding: "1.4rem" }}><div style={{ display: "flex", gap: "1rem", alignItems: "center" }}><span style={{ width: "4rem", height: "4rem", display: "grid", placeItems: "center", borderRadius: "50%", background: "var(--sky)", border: "1px solid var(--ink)", fontSize: "1.5rem", fontWeight: 900 }}>{session.displayName[0]}</span><div><span className="eyebrow">Display name</span><h2 className="display" style={{ fontSize: "2.2rem", margin: ".3rem 0" }}>{session.displayName}</h2><span className="muted" style={{ fontSize: ".8rem" }}>Username: {session.username}</span></div></div></section><AccountRow icon={<UserRound />} title="Class and season" copy={`${session.gameName} · ${session.joinCode}`} /><AccountRow icon={<KeyRound />} title="Change your PIN" copy="Ask your teacher to print a replacement login card or reset your PIN." /><AccountRow icon={<ShieldCheck />} title="Your privacy" copy="This account has no student email address, advertising profile, or real brokerage connection." /><form action={signOutStudent}><button className="button-secondary" type="submit"><LogOut size={17} /> Sign out on this device</button></form></div></>;
}
function AccountRow({ icon, title, copy }: { icon: React.ReactNode; title: string; copy: string }) { return <section className="card" style={{ padding: "1.2rem", display: "flex", gap: ".9rem", alignItems: "start" }}><span style={{ width: "2.6rem", height: "2.6rem", flex: "0 0 auto", display: "grid", placeItems: "center", background: "var(--paper-2)", border: "1px solid var(--ink)", borderRadius: ".65rem" }}>{icon}</span><div><strong>{title}</strong><p className="muted" style={{ margin: ".3rem 0 0", lineHeight: 1.6, fontSize: ".82rem" }}>{copy}</p></div></section>; }
