import { AlertTriangle, Database, Pause, Save, ShieldCheck } from "lucide-react";

import { getTeacherGameDTO } from "@/lib/data/teacher";

export const dynamic = "force-dynamic";

export default async function TeacherSettingsPage() {
  const data = await getTeacherGameDTO();
  if (!data) return null;
  return <><div className="page-title"><div><span className="eyebrow">Season controls</span><h1>Rules & settings</h1><p className="muted" style={{ margin: ".6rem 0 0" }}>Students see these boundaries before they submit an order.</p></div><button className="button-primary" type="button" title="Disabled in public demo"><Save size={16} /> Save settings</button></div><div className="portfolio-layout"><section className="card" style={{ padding: "1.4rem", display: "grid", gap: "1.1rem" }}><div className="field"><label htmlFor="seasonName">Season name</label><input className="input" id="seasonName" defaultValue={data.game.name} readOnly /></div><div className="lesson-grid"><div className="field"><label htmlFor="startingCash">Starting cash</label><input className="input" id="startingCash" defaultValue="$100,000" readOnly /></div><div className="field"><label htmlFor="maxPosition">Maximum single position</label><input className="input" id="maxPosition" defaultValue={`${Number(data.game.maxPositionPercent).toFixed(0)}%`} readOnly /></div></div><fieldset style={{ border: 0, padding: 0, display: "grid", gap: ".7rem" }}><legend className="field-label" style={{ marginBottom: ".5rem" }}>Trading rules</legend><Setting checked label="Allow fractional shares" /><Setting checked={false} label="Allow short selling" /><Setting checked={false} label="Allow margin borrowing" /><Setting checked label="Require a rationale before each order" /></fieldset><div className="field"><label htmlFor="leaderboard">Leaderboard visibility</label><select className="select" id="leaderboard" defaultValue="aliases" disabled><option value="aliases">Class aliases and values</option></select></div></section><aside className="side-stack"><div className="card" style={{ padding: "1.2rem", background: "#e4f5f7" }}><Database size={21} /><strong style={{ display: "block", margin: ".7rem 0 .3rem" }}>Data mode: live IEX</strong><p className="muted" style={{ fontSize: ".8rem", lineHeight: 1.6 }}>Alpaca Basic provides real-time IEX prices for this personal demo. A broader agreement is required before inviting other users.</p></div><div className="card" style={{ padding: "1.2rem" }}><ShieldCheck size={21} /><strong style={{ display: "block", margin: ".7rem 0 .3rem" }}>Student privacy</strong><p className="muted" style={{ fontSize: ".8rem", lineHeight: 1.6 }}>Aliases and PINs are enabled. No student email is required.</p></div><button className="button-secondary" type="button"><Pause size={16} /> Pause all trading</button><button className="button-quiet negative" type="button"><AlertTriangle size={16} /> Archive season</button></aside></div></>;
}
function Setting({ checked, label }: { checked: boolean; label: string }) { return <label style={{ display: "flex", gap: ".7rem", alignItems: "center", fontSize: ".84rem", fontWeight: 720 }}><input type="checkbox" defaultChecked={checked} disabled />{label}</label>; }
