import { Download, KeyRound, UserPlus, UserRoundCheck, UserRoundX } from "lucide-react";
import { notFound } from "next/navigation";

import { addStudent, resetStudentPin, setStudentStatus } from "@/app/actions/teacher";
import { PrintButton } from "@/components/print-button";
import { getTeacherWorkspace } from "@/lib/data/teacher-workspace";
import { formatMoney, formatPercent } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function TeacherRosterPage({ params }: PageProps<"/teacher/games/[gameId]/roster">) {
  const { gameId } = await params;
  const workspace = await getTeacherWorkspace(gameId);
  if (!workspace) notFound();
  const { data } = workspace;
  return <>
    <div className="page-title"><div><span className="eyebrow">Class management</span><h1>Roster & login cards</h1><p className="muted" style={{ margin: ".6rem 0 0" }}>Aliases and PINs keep student access simple without collecting student email.</p></div><div className="page-actions"><PrintButton label="Print login cards" /><a className="button-secondary no-print" href={`/teacher/games/${gameId}/exports/roster`}><Download size={16} /> Export CSV</a></div></div>
    <div className="info-box no-print" style={{ marginBottom: "1rem" }}><KeyRound size={17} style={{ display: "inline", marginRight: 7 }} />Students sign in with class code <strong>{data.game.joinCode}</strong>, their username, and the private PIN you gave them. PINs cannot be recovered; reset one below when needed.</div>
    <div className="portfolio-layout teacher-roster-layout">
      <section className="card table-card"><div className="table-header"><div><span className="eyebrow">{data.classroom?.name}</span><h2 style={{ margin: ".35rem 0 0" }}>{data.roster.length} students</h2></div></div>{data.roster.length ? <div className="table-scroll"><table className="data-table teacher-roster-table"><thead><tr><th>Student</th><th>Login</th><th>Status</th><th>Portfolio</th><th>Return</th><th>Learning</th><th>Actions</th></tr></thead><tbody>{data.roster.map((student) => <tr key={student.id}><td><strong>{student.displayName}</strong><span className="muted table-subtext">Last active {student.lastSeenAt ? student.lastSeenAt.toLocaleDateString("en-US", { month: "short", day: "numeric" }) : "never"}</span></td><td><code>{student.username}</code></td><td><span className="status-pill">{student.status}</span></td><td>{formatMoney(student.equity)}</td><td className={student.returnPercent >= 0 ? "positive" : "negative"}>{formatPercent(student.returnPercent)}</td><td>{student.lessonsCompleted}/{data.activeLessons.length} labs · {student.journalCount} journals</td><td><details className="row-actions no-print"><summary>Manage</summary><div className="row-actions-panel"><form action={setStudentStatus}><input type="hidden" name="gameId" value={gameId} /><input type="hidden" name="studentId" value={student.id} /><input type="hidden" name="status" value={student.status === "active" ? "inactive" : "active"} /><button className="button-quiet" type="submit">{student.status === "active" ? <><UserRoundX size={15} /> Disable login</> : <><UserRoundCheck size={15} /> Restore login</>}</button></form><form action={resetStudentPin} className="pin-reset-form"><input type="hidden" name="gameId" value={gameId} /><input type="hidden" name="studentId" value={student.id} /><label htmlFor={`pin-${student.id}`}>New 4–8 digit PIN</label><div><input className="input" id={`pin-${student.id}`} name="pin" inputMode="numeric" pattern="[0-9]{4,8}" required /><button className="button-secondary" type="submit">Reset</button></div></form></div></details></td></tr>)}</tbody></table></div> : <p className="empty-table-copy">No students yet. Use the form to create the first login.</p>}</section>
      <aside className="card teacher-form-card no-print"><span className="eyebrow">Add one student</span><h2 className="display">Create a login card</h2><form action={addStudent} className="stacked-form"><input type="hidden" name="gameId" value={data.game.id} /><div className="field"><label htmlFor="displayName">Display name or alias</label><input className="input" id="displayName" name="displayName" required maxLength={60} /></div><div className="field"><label htmlFor="username">Username</label><input className="input" id="username" name="username" pattern="[A-Za-z0-9_-]+" required maxLength={32} /></div><div className="field"><label htmlFor="pin">Private 4–8 digit PIN</label><input className="input" id="pin" name="pin" inputMode="numeric" pattern="[0-9]{4,8}" required autoComplete="new-password" /></div><p className="field-hint">Write the class code, username, and PIN on the login card. Only a one-way PIN hash is stored.</p><button className="button-primary" type="submit"><UserPlus size={17} /> Add student</button></form></aside>
    </div>
    {data.roster.length ? <section className="login-card-sheet print-only">{data.roster.map((student) => <article className="student-login-card" key={student.id}><span className="eyebrow">Market Lab login</span><h2>{student.displayName}</h2><dl><div><dt>Class code</dt><dd>{data.game.joinCode}</dd></div><div><dt>Username</dt><dd>{student.username}</dd></div><div><dt>PIN</dt><dd>Provided privately</dd></div></dl><p>Go to stocks.mikesego.com/join</p></article>)}</section> : null}
  </>;
}
